name: ChatGPT Kali Linux Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and run Kali Linux container
      run: |
        docker pull kalilinux/kali-rolling \
        && docker run --tty --detach --privileged --name kali_container kalilinux/kali-rolling

    - name: List installed tools in Kali Linux container
      run: |
        docker exec kali_container apt list --installed

    - name: Stop and remove Kali Linux container
      run: |
        docker stop kali_container
        docker rm kali_container




