name: ChatGPT Kali Linux Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and run Ubuntu container
      run: |
        docker pull ubuntu \
        && docker run --tty --detach --privileged --name ubuntu_container ubuntu \
        && docker exec ubuntu_container apt-get update \
        && docker exec ubuntu_container apt-get install -y <package-name>  # Install any additional packages you need

    - name: Run a command in Ubuntu container
      run: |
        docker exec ubuntu_container ls

    - name: Stop and remove Ubuntu container
      run: |
        docker stop ubuntu_container
        docker rm ubuntu_container



