name: Bard Kali Linux Docker Workflow 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build and run Kali Linux container
      run: |
        docker pull kalilinux/kali-linux-docker
        docker run --tty --detach --privileged --name kali_container kalilinux/kali-linux-docker
        docker exec kali_container apt-get update
        docker exec kali_container apt-get install -y <package-name>  # Install any additional packages you need

    - name: Run a command in Kali Linux container
      run: |
        docker exec kali_container ls -al

    - name: Stop and remove Kali Linux container
      run: |
        docker stop kali_container
        docker rm kali_container
